### ISSUE TITLE
How does defineValidator can be used

### ISSUE THREAD

**Issue by arsalans** [sslotsky/validate-this#1]
I am trying to understand how does defineValidator can be used. Considering your example of define validator on github:
 
```javascript
import email from 'email-validator'
import { defineValidator } from 'validate-this'
 
defineValidator({
  name: 'isValidEmail',
  rule: value => {
    if (value && !email.validate(value)) {
      return 'email_invalid'
    }
  }
})
```
I want to define this validator in a separate typescript file say "email-validator.ts". And I want to use it in my main file called index.ts. How do I export it out from "email-validator.ts" so that it can be used in index.ts file?

Thanks in advance for your help.

**Comment by sslotsky** [comment]
Good question. In fact, it would not need to be exported. If your file were named `customValidations.js`, for example, you could simply

```javascript
import './customValidations'
```

and the `defineValidator` call would be executed as a result of that call.

**Comment by sslotsky** [comment]
Since there is no follow up on this I assume that solved your problem. Closing.
